
## SELECCION DE EMPLEADOS.CSV
RRHH te pide varios recortes concretos de la plantilla.Solo seleccion ,aun no filtramos por condiciones

1. Carga datos/empleados.csv y ponle id_empleado como indice

In [7]:
import pandas as pd

In [44]:
#INDEX_COL PARA COLOCAR INDICE COMO indice_empleados
df=pd.read_csv("C:/Users/USER/Documents/DataScience/01-python-intro/data/empleados.csv",index_col="id_empleado")
df.head(5)

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0

2.  Muestra solo las columnas nombre ,departamento y salario

In [49]:
#Mostrar columnas especificas
df[["nombre","departamento","salario"]].head(10)

                   nombre departamento  salario
id_empleado
1001           Marta Ruiz     Finanzas  44300.0
1002           Elena Sanz         RRHH  22000.0
1003           Ana Prieto       Ventas  58200.0
1004          Laura Gomez    Marketing  24900.0
1005         Paula Torres         RRHH  54800.0
1006           Lucia Mora     Finanzas  49200.0
1007         Javier Nieto           IT  44400.0
1008          Sergio Leon  Operaciones  28600.0
1009          Lucia Nieto  Operaciones  39700.0
1010           Laura Lara     Finanzas  32800.0

3. Muestra las filas de empleados 1003,1007 y 1015 con esas tres columnas

In [ ]:
#USO DE LOC PARA UBICAR UNA FILA EN ESPECIFICO COMO 1003
df.loc[[1003,1007,1015],["nombre","departamento","salario"]]

                   nombre departamento  salario
id_empleado
1003           Ana Prieto       Ventas  58200.0
1007         Javier Nieto           IT  44400.0
1015           Sofia Mora           IT  37100.0

4. Usando ILOC ,muestra las 10 primeras filas y las columnas 1 a 3

In [ ]:
df.iloc[:10,1:4]

            departamento     ciudad  salario
id_empleado
1001            Finanzas   Valencia  44300.0
1002                RRHH     Madrid  22000.0
1003              Ventas     Bilbao  58200.0
1004           Marketing    Sevilla  24900.0
1005                RRHH     Madrid  54800.0
1006            Finanzas   Valencia  49200.0
1007                  IT   Valencia  44400.0
1008         Operaciones  Barcelona  28600.0
1009         Operaciones     Madrid  39700.0
1010            Finanzas    Sevilla  32800.0

5. Ordena la plantilla por salario descendente  y quedate con el top 5

In [50]:
df.sort_values("salario",ascending=False).head(5)

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1032,Diego Gomez,Marketing,Madrid,59500.0,2023-07-14,5.0
1053,Laura Torres,IT,Barcelona,59400.0,2016-03-30,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1062,Diego Prieto,RRHH,Madrid,55600.0,2015-01-06,1.0

6. Ordena por departamento (A-Z) y, dentro de cada uno, por salario descendente.

In [51]:
df.sort_values(["departamento","salario"],ascending=[True,False])

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1055,Carlos Ortiz,Finanzas,Sevilla,43200.0,2019-07-21,3.0
1039,Marta Gomez,Finanzas,Valencia,42900.0,2016-11-05,1.0
...,...,...,...,...,...,...
1054,Pedro Gomez,Ventas,Madrid,41400.0,2022-02-25,2.0
1063,Sofia Torres,Ventas,Barcelona,40000.0,2019-08-31,NaN
1024,Sergio Torres,Ventas,Madrid,25400.0,2019-09-30,3.0
1020,Javier Sanz,Ventas,Madrid,22000.0,2018-02-15,5.0
1048,Sofia Ferrer,Ventas,Barcelona,22000.0,2017-09-16,2.0