In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\USER\Documents\DataScience\01-python-intro\data\ventas.csv")
df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

#Explorar data rapidamente

In [8]:
df['region'].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [9]:
df['region'].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [10]:
df['producto'].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

#SELECCIONAR COLUMNAS

In [11]:
df["producto"].mode()

0    Silla Ergo
Name: producto, dtype: str

In [12]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [16]:
df[["fecha", "region", "unidades"]]

           fecha  region  unidades
0     2024-01-02   Oeste         5
1     2024-01-02     Sur        14
2     2024-01-02  Centro         1
3     2024-01-02  Centro        10
4     2024-01-03     Sur         2
...          ...     ...       ...
1195  2024-12-30    Este         4
1196  2024-12-30    Este        13
1197  2024-12-31   Oeste         2
1198  2024-12-31   Norte         6
1199  2024-12-31   Norte         8

[1200 rows x 3 columns]

In [18]:
df.head(2)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0

In [21]:
#Anexar columnas
df.loc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [25]:
#Anexar filas 
df.loc[0:2, ["producto", "unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [6]:
mascaras=ventas["region"]=="Sur".head()

NameError: name 'ventas' is not defined